### PR TITLE
Performance improvements built

### PR DESCRIPTION
**Pull request by juanca**
Looks like we never opened this PR. 

Not sure if we want to contribute back to base branch.

However, I am opening to track changes.

### CODE REVIEW

**Comment by ahuth** [comment]
@roblevintennis @juanca , the performance improvements work here seems to have caused https://www.pivotaltracker.com/story/show/155492450.

Any thoughts on what the issue could be?

**Comment by juanca** [comment]
Although I opened this PR, I only added changes to be apache 2 compliant.

**Comment by roblevintennis** [comment]
If we've made significant performance improvements, I'd opt for getting this in to the library repo itself if possible.

**Comment by juanca** [comment]
Looks like we just started using upstream. Closing this. 

https://github.com/mavenlink/mavenlink/blob/9b3ee0fe6d07461c5c41fe7a55a80330a6b60e9b/package.json#L89

**Pull request closed without merging**
